version: '3'           #该docker-compose.yml文件使用的版本是 3
services:
  #react-blog
  react-blog:
    build: ./              #指定Dockerfile文件
    restart: always
    image: bmjlinecloud/react-blog:v1              # 镜像名称:版本
    container_name: bmjlinecloud_reactblog
    environment:
      TZ: Asia/Shanghai
    volumes: #挂载数据卷，同步主机与容器的配置文件
      - /data/bmjline/blog/build:/usr/share/nginx/html
      - /data/bmjline/blog/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /data/bmjline/blog/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /data/bmjline/blog/crt/bmjline.com/Nginx:/etc/nginx/crt
      - /data/bmjline/blog/log:/var/log/nginx
    ports:
      - "443:443"                     #指定端口映射
      - "80:80"
